### ISSUE TITLE
Qualifier page blurb to explain page limitations

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#110]
### Overview

as a user who is not currently part of the hackforLA org, I should know the limitations to the search page while going through the qualifier page so that i understand the steps i need to take in order to successfully join hackforla as well as express interest in the roles i am filtering for.

### Action Items

This blurb:

- [x] describes what the qualifier page function is
- [x] what the limitations of the user are as someone who is not part of hackforLA yet

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by patula006** [comment]
**Rough draft.** We may need to wait a bit to finalize so that I can make sure that things are worded correctly. 

Thank you for your interest in volunteering with Hack for LA! Please note that this page is a preliminary page; once you complete this step, you will then have to complete the Hack for LA Onboarding. Once you have completed the Onboarding, you will then be able to view all the specific projects. For now, you will only see a general overview of the project options.

**Comment by sdimran** [comment]
Hi Patty, looks good. I added a few more lines regarding the process and what a potential volunteer can expect when they navigate here. let me know what you think (does this flow well? get our point across? etc.)

Thank you for your interest in volunteering with Hack for LA! Please note that once you select your role interest and availability, you will be able to see an overview of positions within our organization that fit your needs. 

if you are not part of HackforLA at the moment and have not logged in then you be unable to see the  names of the projects and join them, until you have attended an onboarding session where you can learn more about the organization and roles (see link below). 

Once you are registered within the hackforLA network you can then log in and see the exact projects that these roles are for and express the interest to join. (this process is to avoid bombarding our projects and to make sure that new volunteers have an understanding of hackforLA)

**Comment by patula006** [comment]
Cool - thank you! I tried to make it a bit more succinct. Let me know what you think:

Thank you for your interest in volunteering with Hack for LA! Please note that once you select your role interest and availability, you will only be able to see an overview of positions within our organization that fit your needs. You will first need to attend the Hack for LA onboarding, but once you’ve done that, you can then login and see exact projects and express the interest to join (this process is to avoid bombarding our project teams and to make sure that new volunteers first learn more about Hack for LA).

**Comment by Dendorable** [comment]
I also took a stab at the statement.  I reversed it a bit since those with a login will know that you can sort by interest and availability.  

Thank you for your interest in volunteering with Hack for LA!  Please login to see the full descriptions of our available opportunities.  If you do not have a login, simply attend the Hack for LA onboarding to access the full details.  Prior to attending our onboarding,  you may view a list of openings according to your interests and availability.  
We looking forward to working with you.

**Comment by patula006** [comment]
This sounds great - thank you!

**Comment by Dendorable** [comment]
Jen - 

I have provided 2 blubs depending on the space you are trying to fit them in.  They both give across the same idea - just the first blurb is a little clear and more descriptive and the second one cuts in down further in case you need it to fit in a smaller space.  

#1
Please login to see the full descriptions of our volunteer opportunities.  If you do not have a login, simply attend the Hack for LA onboarding to access the full details.  Prior to attending our onboarding,  you may view a list of openings according to your interests and availability.  


#2
Log in for descriptions of our volunteer opportunities.  If you do not have a login, attend the Hack for LA onboarding for full details.  Prior to attending onboarding,  you may view a list of openings according to your interests and availability.

**Comment by patula006** [comment]
These both sound great - thanks!

**Comment by jenchuu** [comment]
@Dendorable @patula006 Thank you!

@graceerya and I will work on placement of this blurb on the qualifier page wireframes.

**Comment by jenchuu** [comment]
@graceerya and I edited the disclaimer a bit more to fit on the qualifier page and search page.

Are we approved to move forward with the below? @sdimran @sharadgaurav7 @Dendorable @patula006

For the qualifier page disclaimer:
You must be logged in to see full descriptions of available opportunities. Currently, you may view a list of openings according to your interests and availability. Please attend onboarding with Hack for LA to access the full details.

For the search page we have a shortened disclaimer:
This is a limited view. Please attend onboarding with Hack for LA to see full descriptions of available opportunities.

**Comment by patula006** [comment]
That wording sounds good to me - thanks, Jen.

**Comment by sdimran** [comment]
@jenchuu -- I am ok with the working as well. 

@sharadgaurav7 please review and advise.

**Comment by sharadgaurav7** [comment]
@jenchuu , I really think the blurb is too long, and takes a lot of space making it very busy for the end user. What if we shortened it and wrote something in lines of" To view full volunteer descriptions please attend an onboarding session". When the user attends the onboarding session they would learn how to come back and log in. 
Let's discuss this in our meeting tomorrow 01/28/22

**Comment by Dendorable** [comment]
If you need it super short:  Attend onboarding for volunteer details.

**Comment by sdimran** [comment]
@hkimsummer can you please update this issue with the final qualifier page blurb that was designed on #77 and we can close this

**Comment by Dendorable** [comment]
@sdimran hkimsummer should not be assigned to this.  
I know we were working on this before with UXD to determine how long the verbiage should be.  We have come up with a few different options for verbiage, but I would need to know how many characters this blurb can support so that I know how short the blurb has to be.  This info would come from the UXD team, but I would be happy to write it after understanding the size restraints.

**Comment by hkimsummer** [comment]
The final qualifier page blurb designed on #77 is as follows: 

"Onboarding with Hack for LA lets you see full opportunities. Learn more"
