### ISSUE TITLE
Figma Access

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/CivicTechJobs#14]
### Overview
We need figma for this project so that we keep all our designs in one place and work collaboratively

### Action Items
- [x] create vault for civic tech jobs
- [x] create vault of ctj - design
- [ ] ~copy figma account from org to new vault~
- [ ] ~add team members who need access to figma to ctj - design~
- [ ] ~copy email accounts to cti-design vault~

**Comment by ihorng** [comment]
Progress: We completed setting up the figma file and passwords on Tuesday, July 27. File is ready.
Blockers: Figma file link cannot be view publicly unless users log into the figma account. I tried to change the settings but I don't have the ability to due to the permission setting assigned to my figma hack for LA login account.

**Comment by ExperimentsInHonesty** [comment]
[Civic Tech Jobs figma workspace](https://www.figma.com/files/team/1040075117587297658/Civic-Tech-Jobs?fuid=775836858007206739)

**Comment by ExperimentsInHonesty** [comment]
We now three vaults in 1password
Civic Tech Jobs - PM
Civic Tech Jobs - UI/UX
Civic Tech Jobs - Dev/Admin

Inside of the Civic Tech Jobs - UI/UX vault there is a link to our figma account so that you can add people and see files
