### ISSUE TITLE
User Flow - Usability Test

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#144]
### Dependency
- [x] #76 
- [x] #160

### Overview

Based on the requirements gathered, the team has created UX design for the user flow that will assist a potential volunteer find their desired opportunity at various projects at HackforLa. We need to test this user flow and make iterations before developing the actual webpages. 

### Action Items

- [x] Review the current user flow with the team
- [x] Create a research plan and share with the team
- [x] Do a mock usability test
- [x] Finalize recruiting message
- [x] Set up Calendly and Zoom link
- [x] Make any needed updates on the design
- [x] Recruit participants 
- [x] Conduct research
- [x] Collate the data, and share with the team

### Resources/Instructions

[Research presentation with findings](https://docs.google.com/presentation/d/15R3H1Jox6h7voPr4hoxTI0SqCesmMxBVaaE58YnKS1s/edit#slide=id.p1)
[Research plan](https://docs.google.com/document/d/1RHWj2SVebM_SAvOFzx9pPy19JoCG-zzqtdqu2Bu5qA4/edit#)
[Usability session notes for each user](https://docs.google.com/spreadsheets/d/1Dm3sOpsEygU7dJkKiwHog8JtqZE0ZHEJG4GpT77r0D8/edit#gid=0)
[Affinity mapping exercise to group insights](https://www.figma.com/file/RjoCVPxki3rU5oOBENZIGT/Usability-Test-1%3A-Affinity-Map?node-id=0%3A1)
[WIP](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by stephaniestahlberg** [comment]
The recruiting message for Slack has been finalized with Bonnie. The message will go out on 3/8 (sent by Bonnie on the new joiner Slack channel), shortly after Monday's onboarding meeting, so we can recruit from the next batch of new volunteers that have not attended onboarding yet. If people don't sign up, our backup plan is to try to recruit directly from Meetup (among people who have signed for upcoming onboarding meetings).

Calendly has been set up with Zoom link 4. I have entered our information in the "Zoom setup" HfLA spreadsheet so that nobody else uses link 4 on the days when we will be doing the testing.

**Comment by stephaniestahlberg** [comment]
Here is a preview of findings from the user research on the new volunteer flow. Full presentation with insights and recommendations to come later.

* Overall, users really like the feel and look of the designs, including the images used, and the general user flow was clear.
* However, there is a loophole in the flow: from the homepage, users can go straight to log in and then sign up with an account, skipping all of the qualifier steps.
* Some returning users would go through the sign-up process again because their first click is not Log in.
* Calendar: different questions and usability issues came up. How to use it, what information to enter, whether a different method would be clearer.
* Project cards page: blurred content creates confusion, different opinions on whether Skills and Meeting Times are required, Program Area is unclear.
* Onboarding: many people miss the warnings, or don’t click on them. The final step of attending onboarding is still not super clear. Even after reviewing the How to join page.
* We received generally positive feedback on the How to join page with some suggestions for improvement.

We're planning to create a prioritization ranking for recommended changes, so it's clear which changes are more urgent and which can be addressed later.

**Comment by stephaniestahlberg** [comment]
Final slide deck with insights and recommendations is [here](https://docs.google.com/presentation/d/15R3H1Jox6h7voPr4hoxTI0SqCesmMxBVaaE58YnKS1s/edit#slide=id.p1). Presented to the team on 3/22/22.
