### ISSUE TITLE
New User Flow Prototype for usability test (UX)

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#160]
### Overview

As a UX Designer we to test the New User Flow prototype to gain necessary data and insights to inform our design decisions and iterations, thereby improving users' experience.

###  Details
 For this issue, we will create a limited New User Flow prototype in Figma and handoff to the UX Researchers to start testing.

**Desktop and mobile flow

### Action Items

- [x] Finish each page revisions
- [x] Connect pages in Figma to create prototype
- [x] Share with UXRs to review and do test run
- [x] Make edits accordingly
- [x] Share with UXRs for review

### Resources/Instructions

[New User Flow Prototype (desktop)](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A16&node-id=2076%3A15177&viewport=250%2C48%2C0.05&scaling=scale-down-width&starting-point-node-id=2076%3A15177)
[New User Flow Prototype (mobile)](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A18&node-id=2094%3A24818&viewport=250%2C48%2C0.08&scaling=scale-down&starting-point-node-id=2094%3A24818)

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by jenchuu** [comment]
@sdimran @sharadgaurav7 Does this fall under Architecture ? Or do we need a new feature for prototypes?

**Comment by ExperimentsInHonesty** [comment]
@graceerya and @jenchuu  This issue is in the prioritized backlog, and it has you assigned to it.  If you are not working on it currently, please remove your assignment or move it to the prioritized backlog.  You may only have one issue assigned to you at a time.

You currently are assigned to waaaaay too many issues
https://github.com/hackforla/CivicTechJobs/issues/assigned/graceerya
https://github.com/hackforla/CivicTechJobs/issues/assigned/jenchuu

I realize that that is a flaw in the way the team has been organizing themselves.  We will be addressing this at the next team meeting.

**Comment by jenchuu** [comment]
@ExperimentsInHonesty 
We are working on it. Just finished editing the mobile and desktop flows for UXRs to use during the usability tests. I'll move to Review column.

**Comment by jenchuu** [comment]
New user flow (desktop)
<img width="1093" alt="New user flow (desktop)" src="https://user-images.githubusercontent.com/88695763/157347631-fad4fc4a-9bde-4168-9d8c-55043f7dd837.png">

New user flow (mobile)
<img width="1094" alt="New user flow (mobile)" src="https://user-images.githubusercontent.com/88695763/157347760-584af613-07e5-4eb5-a4e2-3ad3e83d1783.png">

**Comment by sharadgaurav7** [comment]
@stephaniestahlberg , please confirm if you're able to access this prototype and it is complete. If yes, please close this issue or let us know.

**Comment by stephaniestahlberg** [comment]
Yes, confirmed.
