### ISSUE TITLE
Progress Bar Component (Design System)

### ISSUE THREAD

**Issue by graceerya** [hackforla/CivicTechJobs#168]
### Overview

As designers, we need to create components of the progress bar used in our designs (ie. Qualifier Page) to insert into the design system and share with the dev team.

### Action Items

- [x] Create components/variants
- [x] Review/finalize variants

### Resources/Instructions

[Figma Tutorial: Variants](https://www.youtube.com/watch?v=y29Xwt9dET0&t=193s)
[CTJ Design System Figma Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A2)

**Comment by ExperimentsInHonesty** [comment]
@graceerya This issue is in the prioritized backlog, and it has you assigned to it.  If you are not working on it currently, please remove your assignment or move it to the prioritized backlog.  You may only have one issue assigned to you at a time.

You currently are assigned to waaaaay too many issues
https://github.com/hackforla/CivicTechJobs/issues/assigned/graceerya

I realize that that is a flaw in the way the team has been organizing themselves.  We will be addressing this at the next team meeting.

**Comment by ExperimentsInHonesty** [comment]
@graceerya 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by sdimran** [comment]
@graceerya could you provide an update on this? it has been sitting in the backlog for a month but looks like the components are created already. if complete can we close it?

**Comment by kcoronel** [comment]
Closing this issue as I reviewed the Design System on Figma and found the progress bar component.
