### ISSUE TITLE
Analyze new volunteer survey results

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#171]
### Overview
As a researcher, we need to analyze, summarize and present the new volunteer survey results so they can inform UX tools such as user personas, and we can make data-informed decisions about CTJ. In the survey, new volunteers report what they are looking to gain from the HfLA experience and what they are looking for in a project, and those responses can inform our decision on how to prioritize information in the CTJ project cards. 

### Action Items
- [x] Analyze the first wave of responses to decide if we should make any changes to the survey
- [x] Edit the survey accordingly
- [x] Plan the analysis
- [x] Once we have at least 50 responses, summarize the results and present at the team meeting
- [x] Discuss how we should prioritize information in the project cards based on initial survey results

### Resources/Instructions
- [New volunteer survey](https://docs.google.com/forms/d/e/1FAIpQLSdTM20e-XBD3_fmTPlYfkBKT7cv7aKdO1b2yx_OCrbHLCvLog/viewform)
- [Spreadsheet with survey responses](https://docs.google.com/spreadsheets/d/1tCRcDyEJvz8EXwqa2cfG-yXUz8ctrKuSx4dSzFHHTNc/edit?resourcekey#gid=145746317)
- [Research plan - New volunteer survey](https://docs.google.com/document/d/1XRFXAS7E0NGWVLf6ZcxgD4v9X_Z05aF-uRmcco5JXu8/edit#)

**Comment by sharadgaurav7** [comment]
@stephaniestahlberg , can you please edit and complete this issue

**Comment by sharadgaurav7** [comment]
@stephaniestahlberg , can you please add the details to this issue.

**Comment by stephaniestahlberg** [comment]
One question in the survey was edited to create a new response option: 
"How important are each of these criteria to you when selecting a project to volunteer for?" 
-> added option "Project offers a potential mentor for me" based on one submitted response that had said "Available mentorship" in the Other category.

I also removed the onboarding date question because Google Forms allowed respondents to enter dates in different formats, so the dates could not be easily compared. We already capture the date in which the survey is submitted, and that should match the onboarding date in the vast majority of cases because new volunteers are asked to answer the survey during the onboarding meeting.

The next step requires us to have at least 50 submitted survey responses, and I expect that will take about 2 months.

**Comment by sdimran** [comment]
@stephaniestahlberg  wanted to follow up regarding our submitted responses. are we closer to 50?

**Comment by stephaniestahlberg** [comment]
Hi @sdimran yes, we're getting close. We're at 40 responses now. After the next onboarding meeting on 5/10, we should reach 50+ and we will analyze the results and present to the team shortfly after.

**Comment by stephaniestahlberg** [comment]
@sdimran @sharadgaurav7 Can we move this to prioritized backlog now? @hkimsummer can start working on the 3rd step of planning the analysis, since we're getting close to 50 responses. Thanks.

**Comment by hkimsummer** [comment]
Results were presented on June 14, and here is the [link to the slide deck](https://docs.google.com/presentation/d/1dmjbShEr0uvqCfEduaLpBNisEZL4FVtUUsRh2vhbdlQ/edit?usp=sharing) in our shared drive.

**Comment by stephaniestahlberg** [comment]
@hkimsummer Can you mark all action items as completed and close the issue? Thanks.
