### ISSUE TITLE
One Sheet

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#18]
### Overview
Create onesheet document for civictechjobs so that it can be shared with management team, stakeholder, and funders.

### Action Items
- [x] Check to confirm project does not already have a one sheet
- [x] Make a copy of the one sheet template and store in the product management google drive/one sheet revisions
- [x] Review one sheet and check off items on the checklist to see what it might be missing.
- [x] Setup a meeting with the PM to go over the project to confirm what information on the sheet is up to date and what needs revision.

###
Checklist
- [x] Include project logo (top right)
- [x] Overview
- [x] History and or last 6 months
- [ ] Partners
- [x] Roadmap/next 6 months
- [ ] Contact email (footer)
- [x] Github URL (footer)
- [ ] Link to project page on hackforla.org (footer)
- [x] Slack channel (footer)
- [x] Last updated date (footer)
- [x] Hack for LA logo (bottom right) 

### Resources/Instructions
Check issue #3 for sample one sheets
[One Sheet Template](https://docs.google.com/document/d/1BCNkA3cEox1qp2803r1uDAtffEszQ2P34ZDHo4dKM0Y/edit?usp=sharing)

**Comment by sharadgaurav7** [comment]
In progress file: 
https://docs.google.com/document/d/1BCNkA3cEox1qp2803r1uDAtffEszQ2P34ZDHo4dKM0Y/edit#

**Comment by ExperimentsInHonesty** [comment]
@sharadgaurav7 You overwrote the template with your draft.

This is the file that is supposed to be the template
https://docs.google.com/document/d/1BCNkA3cEox1qp2803r1uDAtffEszQ2P34ZDHo4dKM0Y/edit#heading=h.n7lqzt5pn161

Please make a copy of this file and put it in our folder, and then unwind all the changes you made to the template so that its back to the generic version it was.

**Comment by sharadgaurav7** [comment]
@ExperimentsInHonesty Can you please review this One Sheet:
https://docs.google.com/document/d/1UEbLCswciCrTf5K2nZHxnfNNT7hFOlb3mnfmNfLMgI4/edit#

**Comment by ExperimentsInHonesty** [comment]
@sharadgaurav7 @sdimran Please revise the one sheet so that the top of it conveys succinctly what the project is about.  The where you are and where you are going should be in the history and roadmap portions as bullets.  Having said that, if there is something that absolutely has to appear in the top for context, leave it there.   In the end, the top should be one or two small paragraphs.

Here is what I wrote for the hackforla.org website for this project

> The CivicTechJobs.org MVP website will be a platform to help prospective volunteers find inter disciplinary projects that will be useful for their career development while contributing to positive civic impact and a CMS for Hack for LA projects to be able to list their open roles.

> The tool will match volunteers by availability, role, and program area. Future iterations of the platform will focus helping volunteers find volunteer opportunities that match paid job postings, so that a volunteer can better prepare themselves for the marketplace.

**Comment by sharadgaurav7** [comment]
@ExperimentsInHonesty, please review the updated file:

https://docs.google.com/document/d/1UEbLCswciCrTf5K2nZHxnfNNT7hFOlb3mnfmNfLMgI4/edit#

**Comment by ExperimentsInHonesty** [comment]
Make sure the domain resolves to the project readme, project page at hfla or wiki.

**Comment by ExperimentsInHonesty** [comment]
Make a pdf and upload here https://github.com/hackforla/product-management/tree/master/project-one-sheets
name the document: CivicTechJobs-One-Sheet.pdf

**Comment by sdimran** [comment]
> * [x]  Make a pdf and upload here https://github.com/hackforla/product-management/tree/master/project-one-sheets
>   
>   * [x]  name the document: Civic-Tech-Jobs-One-Sheet.pdf
>   * [x]  Check to see its available at https://github.com/hackforla/product-management/blob/master/project-one-sheets/Civic-Tech-Jobs-One-Sheet.pdf

Completed these items, the onesheet is now available at the project one sheets link above
