### ISSUE TITLE
Change Footer Color

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#182]
### Overview

As a UX Designer, we need to ensure consist use of the color palette throughout the website. We need to change the color of the footer (and potentially the color of the button used in footer) to ensure consistency, currently it is not a color that is in our color palette.

### Action Items

- [x] Change color of footer (comply with WCAG)
- [x] Potentially change color of button used in footer (comply with WCAG contrast)
- [x] Change in design system
- [ ] Update Devs once finalized (Ava is aware of footer color issue)

### Resources/Instructions
[Footer](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=887%3A6489)

**Comment by sharadgaurav7** [comment]
@jenchuu can you please add the right feature label

**Comment by graceerya** [comment]
I have revised the desktop and header footers so that the blue background color adheres to the current dark blue we have in the design system. I also made the button white instead of light blue to comply with WCAG; this color choice may potentially change. The "Donate" button has been made larger on the desktop footer to improve readability.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/64109227/160036242-7068bae9-3d29-47c7-8c25-c3abd08fb23a.png">

**Comment by jenchuu** [comment]
This looks great. Let's roll with it for now! Please change on design system and use component on landing page/other pages.

**Comment by sdimran** [comment]
@graceerya  is this issue complete? you were the last to work on it please let me know

**Comment by sdimran** [comment]
closed after confirming with @graceerya
