### ISSUE TITLE
Revise Read.md

### ISSUE THREAD

**Issue by Rankazze** [hackforla/CivicTechJobs#2]
### Dependency

- [x] #54 

Developer Dependency:

- [x] #49 

### Overview
We want people who come to our repo to be able to find what they need quickly by reading our README.md file

### Action Items

For Product:

- [x] Get draft from #54 
- [x] see example from Guides team wiki
- [x] Edit the civic tech jobs readme file
- [x] Add link to one sheet
- [ ] Make a list of the civic job boards we know about and add it to the readme (see the VRMS link below)

For Developer: 

- [x] Complete the installation instruction portion of the [README.md](https://github.com/hackforla/CivicTechJobs/blob/main/README.md)
- [x] Consult with development on whether the instructions appears correct
- [x] Return this back to the Prioritized backlog, replacing the 'role: backend' label with 'role: product'

### Resources
https://github.com/hackforla/guides/blob/main/README.md
https://github.com/hackforla/CivicTechJobs/blob/main/README.md
[VRMS JobBoard Research](https://github.com/hackforla/VRMS/projects/1#card-36142174)

**Comment by sharadgaurav7** [comment]
@Aveline-art , can you please help edit the Installation instructions for the readme page.

**Comment by Aveline-art** [comment]
@sharadgaurav7 Hi! I would like a couple of clarifications concerning this issue:

1. The issue has a dependency label, and #54 as an uncleared dependency. Should I wait for the dependency to clear before I complete the installation instructions?
2. The label indicates that this is a product issue. Should I switch it to frontend or backend?
3. Am I only completing the installation instructions or should I also complete the other actions item as indicated at [the top](https://github.com/hackforla/CivicTechJobs/issues/2#issue-706003687)?
4. Since I have been assigned directly to this issue, does that imply that this is an urgent issue and I should work on this before working on issues in the Prioritized Backlog and issues I have in progress?

**Comment by sharadgaurav7** [comment]
@Aveline-art ,  I think we duplicated the issues. This issue is to complete the readme part for our project. While the issue #54 has the same action item ("Create an introduction to our project on our read me"). @sdimran , and I just completed the Project intro on readme, as well as on the wiki. We can close the issue #54, if you'd agree - we didn't want to make any change there as the issue was created by you.  Let me know if there's something I missed. 
As for your other questions, 

- Changing the role to backend
- Per our discussion during our weekly call, need your help in completing the Installation Instruction. Product team will fill in the rest of the details. 
- I assigned you directly since we discussed this during our weekly call. Feel free to assign to someone else as you see fit.

**Comment by Aveline-art** [comment]
Got it! I went ahead and closed #54, as well as added instructions for the development portion. I will return this back to the backlog for now and start work some time after completion of my current issue. Hope that works!

**Comment by sdimran** [comment]
Edited a few lines in the "How to contribute" section. updated slack links and wiki links. once Developer instructions are complete, product will review and advise accordingly!

**Comment by Aveline-art** [comment]
Adding a #49 as a dependency on this since the installation instructions are in the contributing.md which is in progress. Developer work should be able to proceed once #103 merges.

**Comment by Aveline-art** [comment]
Reopened, because it was closed accidentially by automation
