### ISSUE TITLE
Search result page - Lu's design

### ISSUE THREAD

**Issue by fenglugithub** [hackforla/CivicTechJobs#285]
### Overview

We need to design a search page with filters so that a user can easily find a volunteer opportunity that fits their skills or goals.

### Action Items

- [x] Ideate 
- [x] Present to the team
- [x] Feedback
- [x] Iterate
- [x] present to the team
- [x] Feedback

### Resources/Instructions

[Requirements](https://docs.google.com/spreadsheets/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=477987515)
[Lu's design - figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4404%3A20373)

**Comment by sdimran** [comment]
Hi @fenglugithub, we have an existing issue for the search page design as well as each component that is being worked on #24 , can we leverage those instead of creating a new issue? that one is currently in the prioritized backlog so you can simply assign yourself it and pull it into the actively working column to post and continue on.

**Comment by jenchuu** [comment]
@sdimran we are changing how we work on it; I'm deleting the P1-P4 issues grouping by section.
