### ISSUE TITLE
Emergent Requirements Meeting Agenda

### ISSUE THREAD

**Issue by salimays** [hackforla/CivicTechJobs#348]
### Overview

As we get closer to an MVP launch in March, we need to review and align with the requirements and go over remaining open questions.

### Action Items

- [x] Item 1: How to acquire jobs data? The conversation with Danish in the summer of 2022 led to a manual entry solution on GitHub on the back end with developers working on it regularly to make it visible on the front end
- [x] Item 2: Regarding the CMS, we'll review wireframes.
- [x] Item 3: Re-discuss general requirements and vision.

### Resources/Instructions
[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
https://www.when2meet.com/?18699149-mcI7b
[Meeting recording](https://drive.google.com/drive/folders/1txJPTGYrfMSaszt6N2j-EbzdjVS7WPLk?usp=share_link)

**Comment by kcoronel** [comment]
Notes, from meeting: 

CMS: 

[Figma Design](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=6294%3A65136): 

Ava: System that displays posting, but no way to get posting into our system. 

What kind of data? Job posting data (job description, role, tools people need to know) 
Job descriptuon would come from PM - civic tech job 
role type- people depot- pre-defined 

MVP- need a logging in systtme and a way for people to create postings 

What would it be if it didn't have the before": 
not involve too much developer, no point to create alternative system, 
team doesn'tt need tto be completely hands off 

Have to open tocket on website and developer has to make teh change 

Bonnie shared screen to share the product open roles - no develiper help 

civic tech jobs is replacing the CoP job boards 

need to serve people who need to see jobs and those who are postitng them 

Best thing- google form - google will save and store something in a format that is easy and organized 

API host 

a bit of latency - add data/read it and upload it 

Good temporary solution - Google form - host jobs, but it won't let you remove jobs - might be possibke with a google form, form could say adding a job or removing job, give us the job ID - do it manually - make it so that only folks with hackforla email addresses (can make all forms), folks use project email to submit form 

rebuild postings every night from data of spreadsheet- allow people to edit postings - when sumbitting, save link at end/send copy of responses - they could edit it 

need to make a call for every row - and wouldn't be able to import an entire spreadsheet and paste it to a JSon file 

expose an API, but would still be risky 

Bonnie questuon: where are we withd designs for the job postings page that PM will access to enter job posting -- 6-months (optimisttic) 8 months to a 1 year (realistic) 

difficulty of level had with the wins page- and how it broke, w/o more convo, understand may want to make postings accessible, etc. should not be prioritized 

constituency is from PMs 



Come up with instructions, interim step 

design team - input pages- work in progress 

almost done with front-end and need work backend 


Google forms salima shared - project interest form will be own interface, will not be form 


Bonnie suggestion: may be less practical, have a system of users logging in and authenticating, everyone is on VRMS, right now, on the meeting times, can say, Salima is able to edit times for Civic Tech Jobs, when she logs in she will be able to make this a direct page 

no longer tickets on VRMS 

Ask them to see if they can vhange roadmap; allow same people with meeting time to post roles 
 
Not a good idea 

Salima - design team- make a presentation for where they are 
doesn't have to be fancy, see screens 

Get designs done 
Work good enough 


Post design - just pages - 2 months at least 

CMS: 
will have edits 

salima and karen - come to next onboarding - put in room with senior developer - pitch about project and show them where they can find all projectts - next one on 2/28 

probably not release - 

developer - live feedback - recruiting people, testing out; send ui/ux people to onboarding and have them show everybody the projects like product or development; test it with the actual users, is this clear enough, url that disappears after a day 

url only for testing; show them staging environment 

works across regular communitty paractice, and then the rest? 

backend data wise- roll a cop as a project and start data in the same way; can have a meeting with dave - 3rd friday of the month at 1pm 


Where is project data - VRMs, website

**Comment by kcoronel** [comment]
@salimays @ExperimentsInHonesty when you get a chance can you please add the recording from Sunday's meeting
