### ISSUE TITLE
Preference Test - Landing Page Design Options

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#42]
We need to conduct a preference test for the landing page to choose one of the three final designs. Once we have the final visual design chosen, we can proceed to usability testing different copy length versions.

### Action Items:
- [x] write up a research plan
- [x] create preference test w/ questions at the end
- [x] create 3 different versions of the survey
- [x] randomize the survey version that participants see and post to the #general slack channel
- [x] analyze survey results
- [x] choose visual design based on results
- [x] choose final landing page design from different copy length options

### Resources:
3 design options to test "Final Design Options V4"
https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7

**Comment by stephaniestahlberg** [comment]
We have created a [Research Plan](https://docs.google.com/document/d/1X2YkfzSYeDZM5wKx58yxUnv3CNG94KfV2HgRpZPgZx8/edit#) for testing the different versions of the new webpage, and a [Google Form](https://docs.google.com/forms/d/e/1FAIpQLScSTXKbJy425-kSCaylG8n49TpN9bxUECRSwWke9tfQRnHqSA/viewform) to conduct the preference testing. We will discuss at the next meeting, and why preference testing instead of A/B testing.

**Comment by jenchuu** [comment]
@ExperimentsInHonesty We need feedback and would like to post to the General channel on Slack hopefully by tomorrow. Please advise if ok?  @Aveline-art kindly agreed to help us create a randomized link to the Google form. We'll send once it's ready.

**Comment by stephaniestahlberg** [comment]
3 versions of the Google Form, so that 1/3 of participants see [version A first](https://docs.google.com/forms/d/e/1FAIpQLScSTXKbJy425-kSCaylG8n49TpN9bxUECRSwWke9tfQRnHqSA/viewform), 1/3 see [version B first](https://docs.google.com/forms/d/e/1FAIpQLScPR4yOxnYtk9pxA9nA0IQdYxqHgAcCoS1O6gT536eOA1rytw/viewform), and 1/3 see [version C](https://docs.google.com/forms/d/e/1FAIpQLSeldvsdfAZU1BViLBR1su7_uk_0nuOCDJuJfHd4R4RYCAuHZA/viewform) first.

**Comment by Aveline-art** [comment]
@stephaniestahlberg This is the link to the random redirect: aveline-art.github.io/civic-tech-jobs-survey

One note: The randomizer does not guarantee that sample sizes will remain the same for each survey. As an example: for the number of responses for survey A/B/C, it is possible to get a 10/10/10 response distribution as is 10/16/4 (although the chances of this is very low). I hope that is fine!

**Comment by patula006** [comment]
Thank you, Ava. The sample size differences (if that happens) is fine.
Stephanie's suggested wording for the post in the General channel is great:  "Hi! We are designing a new webpage for the volunteer roles board and would really appreciate your feedback. Please take our quick 1-minute survey by clicking [here](https://aveline-art.github.io/civic-tech-jobs-survey)."

**Comment by patula006** [comment]
[HfLA UX Research Volunteer Boards Page.pptx](https://github.com/hackforla/CivicTechJobs/files/7508977/HfLA.UX.Research.Volunteer.Boards.Page.pptx)

**Comment by jenchuu** [comment]
Based on chosen landing page design, below are different copy length options:

![Landing page options (copy lengths)](https://user-images.githubusercontent.com/88695763/141041007-89cac656-a76f-473f-bb0a-329ff978231b.png)

**Comment by jenchuu** [comment]
Based on our meeting discussion, this is the chosen landing page (mobile version to follow):
<img width="1446" alt="Chosen landing page design" src="https://user-images.githubusercontent.com/88695763/141041162-190e8a0f-40ec-45f5-986a-592bc4a4b06f.png">
