### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#49]
### Dependency

- [x] #25 

### Overview
As a developer, we need to give guidance to future developers on how to set up their environment and contribute to our project. For this issue, we will write a contributing.md file for developers.

### Action Items

- [x] If it does not already exist, create a file called contributing.md in the root directory
- [x] In this file, write out steps to set up the development environment and links to key getting started documentation in our wiki
- [ ] Release dependency on #2

### Resources/Instructions
[Sample contributing.md from another project](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

**Comment by Aveline-art** [comment]
Question for the team:

The contributing.md guide is tailored for developers. Do other departments also have their own version of a contributing guide? If so, can I link them to the contributing.md?

**Comment by sdimran** [comment]
> Question for the team:
> 
> The contributing.md guide is tailored for developers. Do other departments also have their own version of a contributing guide? If so, can I link them to the contributing.md?

This is a good Question @Aveline-art . @jenchuu @patula006 if you have any documentation specific to your areas please let Ava know and we can make one Contributing.md file with a table of contents

**Comment by Aveline-art** [comment]
Update: @sdimran will take over the issue and return back to me with information for the "contact us" section of the contributing guide.

**Comment by sdimran** [comment]
> Update: @sdimran will take over the issue and return back to me with information for the "contact us" section of the contributing guide. Until this is finished, the linked PR, #103, is set to draft.

Hi @Aveline-art I looked into this by browsing multiple other projects at hackforla to see how they are displaying this information. there doesn't seem to be a consistent method of displaying contact info (some projects have slack, some have project email, others have the emails of each of the leads, as well as combinations of the above). I think because any freelance contributor will have to already be a part of hackforLA in order to view the repositories we are okay to use our slack channel as well as the project email in the below format:

To reach our team with questions or comments, you can slack us on the #Civictechjobs channel on Slack or email Civictechjobs@hackforla.org. 

Please let me know if that makes sense

**Comment by Aveline-art** [comment]
Thank you for getting back to me!

> any freelance contributor will have to already be a part of HackforLA in order to view the repositories

I'd like to correct that this is not the case, since our repository is public (see below image showing our repository while not signed in). 

<img src="https://user-images.githubusercontent.com/62368440/148588388-fad22bee-9324-4010-9aa9-a9c291c9dcdd.png" width="600" height="300" />

The slack channel or email is fine with me, but please let me know if the above correction changes your mind. 🙂

**Comment by sdimran** [comment]
Ahh alright, thank you for correcting me I did not realize the repo was public! lets follow through with the same answer as above regardless. if it gets troublesome in the future then we can adjust accordingly
