### ISSUE TITLE
Summarizing our project for official GitHub documentation

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#54]
### Overview
As a developer, I would like our documentation to succinctly and effectively summarize our project for new, potential developers. For this issue we will come up with a project summary for our read me and wiki.

### Action Items

- [x] Create an introduction to our project on our read me
- [x] Create an introduction to our project on our wiki homepage
- [x] Get approval from the team on the introduction
- [x] Release dependency on:
  - [x] #2  

### Resources/Instructions
[README.md](https://github.com/hackforla/CivicTechJobs/blob/main/README.md)
[Wiki home](https://github.com/hackforla/CivicTechJobs/wiki)

**Comment by Aveline-art** [comment]
Questions:

1. Which role does this issue belong to?
2. What criteria do we have for an intro to our project?
3. Who needs to review the intro and approve it?

**Comment by sdimran** [comment]
Hi @Aveline-art, I made a few edits to the project description in the readme.md file in the main branch. added to the the project description as well as included a few links to the technology used. regarding the installation instructions, is there anything specific from a developers end that we need to include? I am not 100% sure if the information already there is the most up to date and in line with how the project is set up

**Comment by sdimran** [comment]
Below is the current introduction for action item 1 in this ticket

CivicTechJobs is a project of Hack for LA. CivicTechJobs helps technology practitioners interested in having civic impact to find job opportunities from a central hub of listings. The website's main features include a linklist to public interest job boards and other resources relevent to their focused journey to work on projects and solve problems with a public benefit.

The CivicTechJobs.org MVP website will be a platform to help prospective volunteers find inter disciplinary projects that will be useful for their career development while contributing to positive civic impact and a CMS for Hack for LA projects to be able to list their open roles.

The tool will match volunteers by availability, role, and program area. Future iterations of the platform will focus helping volunteers find volunteer opportunities that match paid job postings, so that a volunteer can better prepare themselves for the marketplace.

**Comment by Aveline-art** [comment]
Putting this into 'New Issue Approval' because I am unsure where to place it in the prioritized backlog without a milestone.

**Comment by sdimran** [comment]
Hi Ava, I think we can keep this under the Project Setup milestone as the documentation will act as a go-to resource for new joiners to understand what we are doing. let me know what you think

**Comment by Aveline-art** [comment]
Hi @sdimran! I am not too sure what milestone it should be, since I don't know what exactly each milestone entails. You can decide whichever fits best based on what the project needs?

**Comment by Aveline-art** [comment]
Closed because items are completed
