### ISSUE TITLE
Feature Suggestion: Enable Vite Hot Module Reloads in development mode

### ISSUE THREAD

**Issue by LoTerence** [hackforla/CivicTechJobs#563]
### Overview

As a developer I want to develop the frontend application without having to restart the server on every new code change.

### Action Items
- [x] Enable vite HMR in development mode
- [x] Integrate vite frontend with django backend
- [x] Make sure it works in docker

### Resources/Instructions
If there is a site which has documentation that helps with this issue provide the link(s) here:
- https://vitejs.dev/guide/features.html#hot-module-replacement
- https://vitejs.dev/guide/backend-integration.html

**Additional context**

**Comment by kcoronel** [comment]
Hi @LoTerence I updated this issue with a Milestone 

Can you explain why you added this issue to the 'Ready' column? 

@nooriaali9 what is the type of workflow you would like Devs to have as they create issues? Some projects create issues and leave or place them in the 'New Issue Approval' and assign them to you (as our PM managing Kanban) and you release the issue to the appropriate column or re-assign it to the person who created the issue so that they can fix the issue ex: Add milestone, be more descriptive, etc. Another way projects manage issues is for the issue to be assigned to the Team Lead instead of the PM. The same process outlined above happens, the change is that the Team Lead manages releasing the issue to the appropriate column or return it to the issuer. @JimmyJuarez10 and @nooriaali9 what process would we like to share with the team?

**Comment by LoTerence** [comment]
Hi Karen, Thank you for updating the issue. This is my first issue / PR workflow in HfLA so I'm still not totally familiar with the standard processes.

I thought "ready" column meant "ready for review" 😅 But I see that I was wrong now. Which column should it be in? I will move it right away.

Is there any documentation that explains the standard issue workflow in more detail?

**Comment by kcoronel** [comment]
No worries at all! Its helpful for me and the product team to understand how people are interpreting things so thank you! 

We will get back to you re: workflow. I would like to hear what @nooriaali9 and @JimmyJuarez10 feel is best and are comfortable with.

**Comment by nooriaali9** [comment]
> Hi @LoTerence I updated this issue with a Milestone and a 'Role' label
> 
> Can you explain why you added this issue to the 'Ready' column?
> 
> @nooriaali9 what is the type of workflow you would like Devs to have as they create issues? Some projects create issues and leave or place them in the 'New Issue Approval' and assign them to you (as our PM managing Kanban) and you release the issue to the appropriate column or re-assign it to the person who created the issue so that they can fix the issue ex: Add milestone, be more descriptive, etc. Another way projects manage issues is for the issue to be assigned to the Team Lead instead of the PM. The same process outlined above happens, the change is that the Team Lead manages releasing the issue to the appropriate column or return it to the issuer. @JimmyJuarez10 and @nooriaali9 what process would we like to share with the team?

Hey Karen! The devs can assign the issue to me, and I will have a look at whatever needs updates - and move it to whatever column seems right. I'm sure our tech lead has enough on their plate anyway.

**Comment by kcoronel** [comment]
@LoTerence fyi we moved this issue to the 'New Issue Approval' column, and will be sharing an outlined workflow next week :)

**Comment by LoTerence** [comment]
Issue was resolved and merged on 09/12/2024
