### ISSUE TITLE
Task and User Flow

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#76]
### Overview

As a UX Designer, we need a clear understanding of users' journey while using Civic Tech Jobs' website. 

Based on the latest requirements, we will create a **task flow** to define the linear high-level steps all users must complete to accomplish their task.
We will also create a **user flow** to illustrate the path our main user-type may take.

### Action Items

- [x] Task flow
- [x] User flow
- [x] EDIT task and user flow

### Resources/Instructions
[Civic Tech Jobs' Task and User Flow](https://whimsical.com/ctj-task-and-user-flow-8GgB5Moy14fnQDv24o1fGC)

[Civic Tech Jobs' Figma Prototypes](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A16)

[Meeting Notes for Bonnie's Feedback on Flow - 02/06/22](https://docs.google.com/document/d/1MMqd0v3sYEF-ciziup3h1jHUPPK1o8PL1xwbkF_ygeE/edit?usp=sharing)

[https://medium.com/erika-harano/ux-task-flows-versus-user-flows-as-demonstrated-by-pancakes-896e78a98026](https://medium.com/erika-harano/ux-task-flows-versus-user-flows-as-demonstrated-by-pancakes-896e78a98026)

**Comment by jenchuu** [comment]
[task and user flow](https://whimsical.com/ctj-task-and-user-flow-8GgB5Moy14fnQDv24o1fGC)

**Comment by sharadgaurav7** [comment]
@jenchuu , let's discuss the dependency "Requirement Changes" you have mentioned in the issue before moving this in the prioritized backlog.  Looks like this issue is nearly complete as you have already prepared the user flow

**Comment by jenchuu** [comment]
@sharadgaurav7 Sounds good; I unfortunately missed last weeks meeting so I put dependency as "requirement changes" in case there were any further changes to the Requirements that I missed. (I did check the updated Requirements google sheet)

**Comment by jenchuu** [comment]
[V3 of task and user flow](https://whimsical.com/ctj-task-and-user-flow-8GgB5Moy14fnQDv24o1fGC)

![V3 CTJ Task and User flow](https://user-images.githubusercontent.com/88695763/149209441-dcdcd320-61da-454f-9984-ec223f278d07.png)

**Comment by jenchuu** [comment]
@sharadgaurav7 @sdimran. Is this flow approved as starting point for the MVP?

@Aveline-art Is it possible to change WHERE the "Join us" CTA on home page and CoP cards lead to when a user is LOGGED in? Aka can users be directed to FULL search page?
(These "Join us" CTAs lead to qualifier page when NOT logged in)

![CTJ Task and User Flow@2x](https://user-images.githubusercontent.com/88695763/151239120-bd749a57-8bcc-4fac-8173-69e16b591fab.png)

**Comment by Aveline-art** [comment]
@jenchuu That should be very possible!

**Comment by sharadgaurav7** [comment]
Team, 
Since the first time users' details will not be captured without their login credentials being activated, they will have to login and go through the qualifier page again after they receive their login credentials (following the Onboarding session). The only way the website can remember previous inputs will be if we drop some cookies (this will not be permanent). 

@Aveline-art , can you please comment on this thought process. We can discuss this on slack if needed. Or during our Tuesday meeting.

**Comment by Aveline-art** [comment]
@sharadgaurav7 A couple of points:

- Is there a specific reason why users are allowed access to the qualifier page without logging in?
- On a side note, in case there happens to be a specific reason, could we encourage (optional) user login through some warning text? Ex: "We encourage you to sign up so that we can save your input from this page! This will...[benefit to the user]."
- Cookies/localstorage are relatively stable. Cookies can expire, based on a set date (up to months/years), and localstorage can be manually deleted by a user.

**Comment by jenchuu** [comment]
Per discussion with @Aveline-art and @graceerya below is the revised task and user flow.
We would love to go over this task/user flow and the prototype flow we created with you tomorrow evening! @sdimran @sharadgaurav7 

![CTJ Task and User Flow@2x (1)](https://user-images.githubusercontent.com/88695763/152633078-71f3503a-1568-4680-af3c-fa9e1b74d6ed.png)

**Comment by sdimran** [comment]
@graceerya  you can include the notes and feedback from bonnie regarding the proposed flow here. can we also include a link to the figma in the resources to indicate where the protoypes presented are?

Thanks!

**Comment by sharadgaurav7** [comment]
@jenchuu , I think this issue is complete. Can you please close it. 

There's another issue ( #144 )that has dependency on this one, for the issue #144 to be active, this one has to be completed.

**Comment by jenchuu** [comment]
Yes done. Moved to Review column.

**Comment by sharadgaurav7** [comment]
@jenchuu , please make sure a copy of this is on the shared drive. Closing this issue, thank you for the works here!
