### ISSUE TITLE
civictechjobs.org website logo

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#8]
### Overview
We need a logo for the project so that we can appear on the hackforla.org homepage and recruit.  The logo should encourage people to use our application to find civic jobs

### Action Items
- [x] Identify values and other properties that will help us understand if the logo design meets requirements
- [x] UX team to create a logo for the new civictechjobs.org

### Resources/Instructions
[Figma]()

**Comment by ihorng** [comment]
Design Round # 1

![Ingrid-CivicTechJobs-Logos](https://user-images.githubusercontent.com/63479928/125541603-27016285-b6c9-43bb-a06f-ccb953f8f821.png)

**Comment by sharadgaurav7** [comment]
Thanks @ihorng 

Per our discussion, we need to remove the magnifying glass from the logo since civic tech index team already uses that.

**Comment by ihorng** [comment]
Design Round # 2
<img width="795" alt="Ingrid-CivicTechJobs-Logos-Round2" src="https://user-images.githubusercontent.com/63479928/126009295-b18946e3-df7d-4d1c-8735-61352dc84184.png">

Logo Notes:
1. Person raising hand up = individual interest in contributing
2. Group of individuals = Team / Community / Network
3. Abstract C #1
4. Abstract C #2
5. Wordmark with Hack for LA’s triangle logo used as a period

**Comment by Aveline-art** [comment]
@ihorng I am loving 2 and 3, but they all look amazing! The colors are pretty close to Civic Tech Index though, and I am not sure if we are related them them? I am not much of a color person, so no suggestions from me. Maybe someone else will have a better idea.

**Comment by cherrijeong** [comment]
![civictechjobs](https://user-images.githubusercontent.com/79132442/126022864-177a9db0-4681-4a00-ae2b-d0f5bc8dbdb2.jpg)

Here are more sketches for review/ideas, open for color suggestions!

**Comment by sharadgaurav7** [comment]
@ihorng What do those semi-circles represent? I personally like 1C, and 5B. They are cleaner

@cherrijeong : Is there relevance to the extended J's? I like the one where the word 'tech' is in a black highlight. It would help if you can number these. 

We should select a few of the best and submit a poll from other team members on slack. What do you guys think? @sdimran

**Comment by ihorng** [comment]
@sharadgaurav7 Do you mean logo # 1 when you are referring to the "semi-circles"? It's a person raising then hand up to represent interest in contributing. It is also an abstract image of letter C (when titling your head sideways). Colors are not finalized yet because Cherri and I want to first get an idea of the directions of the logo. Colors can be easily adjusted.

@cherrijeong I like # 1 and # 3 (the last 2 designs with the long "j." - i'm also curious about your thought process about making the "j" extended and removing the "hook" of the "j") . As a general comment, I am wondering if the words "Civic Tech" should be bigger. Currently, the word "Job" is heavily emphasized and its the first thing my eyes are drawn too. I am curious to see how it will look when its a smaller logo and wonder if "Civic Tech" might be visible enough.

**Comment by sdimran** [comment]
I really like 1C and 4C from @ihorng's second design round. the abstract image of someone raising their hand looks unique. regarding color scheme I echo @Aveline-art. I really like the blues but if they are the same or indistinguishable from civic tech index then I think it would be valuable to discuss at the next team meeting. 

@cherrijeong I like the last 2 on the last column because it really highlights that this is targeted for jobs. the wave above the J also gives me "indeed" vibes. can we see this with just one semicircle rather than the two?

@sharadgaurav7  agreed I think it would be valuable to narrow down a list of top 3 -5 internally then take it to  the design and PM CoP slack channels/meetings for feedback. we can discuss in detail at our team meeting tomorrow

**Comment by ihorng** [comment]
Below are the logo selections to submit for the logo poll.

![CivicTechJobs-Logos-Poll](https://user-images.githubusercontent.com/63479928/127034680-11833d63-a06c-4410-9aa2-bfb6eb0984fa.jpg)

**Comment by ihorng** [comment]
Below are 2 logo color options. These are very quick mock ups to show the color palette being used throughout the page at a high level.

Please note:
-  the detail aspects were not focused
-  the logo used in the mockup is not the finalized logo and is only used as a placeholder
-  for the footer, since it will need to be redesign, I colorblocked the section with the background color.

![Color #1](https://user-images.githubusercontent.com/63479928/127202764-a65f5315-ef22-4ee7-9cc8-1bdd2a267e6f.png) 

Option 1: Blue - represents trust, communication, purpose

![Color #2](https://user-images.githubusercontent.com/63479928/127202780-e85f9298-b3ac-4ee9-b2ef-69aca2269bcd.png)

Option 2: Indigo (mixed of blue and purple) - in addition to the values of blue, purple represents creativity and inspiration

**Comment by patula006** [comment]
Hi, Ingrid - I think I like #1 (blue) better as it's more familiar. Thanks - Patty
